# FROM almalinux:9
# CMD ["ping","google.com"] # google.com will work through termnal w ecan override


# FROM almalinux:9

# ENTRYPOINT ["ping","google.com"] # google .com will come but w ecan't override through terminal

FROM almalinux:9
CMD ["google.com"]
ENTRYPOINT [ "ping" ]