ARG version
FROM almalinux:${version:-8}
ARG COURSE="Docker" \
    TRAINER="Siva" \
    DURATION="10HRS" \
    AUTHOR="JoinDevops"
RUN echo "Trainer is: ${TRAINER}"    
CMD ["sleep","100"]


# ARG version
# FROM almalinux:${version:-8}
# ARG COURSE="Docker" \
#     TRAINER="Siva" \
#     DURATION="10HRS" \
#     AUTHOR="JoinDevops"
# RUN echo "Trainer is: ${TRAINER}", version is: ${version}"

# CMD ["sleep","200"]